"""Deterministic browser persona generation from userId.

Mirrors ``lib/browser-persona.js`` from the Node.js camofox-browser.

Every userId always produces the same persona deterministically.
Managed profiles (e.g. ``leboncoin-cim``, ``vinted-main``) get fixed overrides;
all other userIds get a pseudo-random persona seeded by SHA-256.
"""
from __future__ import annotations

import hashlib
from typing import Any, Optional

from camofox.core.utils import normalize_user_id

# ---------------------------------------------------------------------------
# Constants — kept in sync with lib/browser-persona.js
# ---------------------------------------------------------------------------

PERSONA_OS: list[str] = ["windows", "macos", "linux"]

PERSONA_LOCALES: list[dict[str, Any]] = [
    {
        "locale": "en-US",
        "timezoneId": "America/New_York",
        "geolocation": {"latitude": 40.7128, "longitude": -74.006},
    },
    {
        "locale": "fr-FR",
        "timezoneId": "Europe/Paris",
        "geolocation": {"latitude": 48.8566, "longitude": 2.3522},
    },
    {
        "locale": "en-GB",
        "timezoneId": "Europe/London",
        "geolocation": {"latitude": 51.5074, "longitude": -0.1278},
    },
    {
        "locale": "de-DE",
        "timezoneId": "Europe/Berlin",
        "geolocation": {"latitude": 52.52, "longitude": 13.405},
    },
]

# Cross-OS safe screen sizes that camoufox-js can satisfy.
PERSONA_SCREENS: list[dict[str, int]] = [
    {"width": 1536, "height": 864},
    {"width": 1728, "height": 1117},
    {"width": 1920, "height": 1080},
]

PERSONA_HARDWARE_CONCURRENCY: list[int] = [4, 6, 8, 10, 12, 16]
PERSONA_DEVICE_MEMORY_GB: list[int] = [4, 8, 12, 16, 24, 32]
PERSONA_DEVICE_SCALE_FACTORS: list[float] = [1, 1.25, 1.5, 2]

MANAGED_LEBONCOIN_VISIBLE_DISPLAY: dict[str, int] = {"width": 1920, "height": 1080}

FRENCH_RESIDENTIAL_LOCALE_PROFILE: dict[str, Any] = {
    "locale": "fr-FR",
    "languages": ["fr-FR", "fr", "en-US", "en"],
    "timezoneId": "Europe/Paris",
    # Coherent with Julien's home region / French-residential use case.
    "geolocation": {"latitude": 46.2044, "longitude": 6.1432},
}

# Managed browser personas — fixed overrides for known userIds.
# WebGL is now generated by pythonlib (camoufox.webgl.sample_webgl).
# Phase 2: Replace buildBrowserPersona with pythonlib fingerprints.
# For now, leave webgl unset — camoufox-js uses real browser values.
MANAGED_BROWSER_PERSONAS: dict[str, dict[str, Any]] = {
    "leboncoin-cim": {
        "screen": {"width": 1920, "height": 1080},
        "hardwareConcurrency": 8,
        "deviceMemory": 16,
    },
    "leboncoin-ge": {
        "screen": {"width": 1680, "height": 945},
        "hardwareConcurrency": 6,
        "deviceMemory": 12,
    },
    "vinted-main": {
        "screen": {"width": 1440, "height": 900},
        "hardwareConcurrency": 8,
        "deviceMemory": 16,
    },
    "emploi": {
        "screen": {"width": 1600, "height": 900},
        "hardwareConcurrency": 8,
        "deviceMemory": 16,
    },
    "emploi-candidature": {
        "screen": {"width": 1600, "height": 900},
        "hardwareConcurrency": 8,
        "deviceMemory": 16,
    },
    "emploi-officiel": {
        "screen": {"width": 1440, "height": 900},
        "hardwareConcurrency": 6,
        "deviceMemory": 12,
    },
    "courses": {
        "screen": {"width": 1536, "height": 864},
        "hardwareConcurrency": 8,
        "deviceMemory": 16,
    },
    "courses-auchan": {
        "screen": {"width": 1366, "height": 768},
        "hardwareConcurrency": 6,
        "deviceMemory": 12,
    },
    "courses-intermarche": {
        "screen": {"width": 1600, "height": 900},
        "hardwareConcurrency": 8,
        "deviceMemory": 16,
    },
}

# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _deterministic_index(user_id: str, salt: str, size: int) -> int:
    """Deterministic index into a pool of *size* items using SHA-256.

    Matches Node.js ``digest.readUInt32BE(0) % size``.
    """
    data = f"{salt}:{user_id}".encode()
    digest = hashlib.sha256(data).digest()
    return int.from_bytes(digest[:4], "big") % size


def _clamp_screen(
    screen: dict[str, int],
    bounds: Optional[dict[str, int]] = None,
) -> dict[str, int]:
    """Clamp screen dimensions to not exceed the visible display bounds."""
    if bounds is None:
        bounds = MANAGED_LEBONCOIN_VISIBLE_DISPLAY
    return {
        "width": min(screen["width"], bounds["width"]),
        "height": min(screen["height"], bounds["height"]),
    }


def _build_managed_browser_persona(user_id: str) -> Optional[dict[str, Any]]:
    """Build a persona for a managed user ID, or return None if not managed."""
    profile = MANAGED_BROWSER_PERSONAS.get(user_id)
    if profile is None:
        return None
    return {
        "os": "windows",
        "localeProfile": FRENCH_RESIDENTIAL_LOCALE_PROFILE,
        "screen": _clamp_screen(profile["screen"]),
        "hardwareConcurrency": profile["hardwareConcurrency"],
        "deviceMemory": profile["deviceMemory"],
        "deviceScaleFactor": 1,
        "webgl": None,
    }


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def build_browser_persona(user_id: str) -> dict[str, Any]:
    """Deterministically build a browser persona from a *user_id*.

    Same *user_id* always produces the same persona.
    If *user_id* is in :data:`MANAGED_BROWSER_PERSONAS`, returns a fixed
    persona with ``os='windows'`` and French residential locale profile.
    Otherwise, uses SHA-256 hashing to pseudo-randomly select all parameters.

    The returned dict matches the shape expected by camoufox-js:

    .. code-block:: python

        {
            "version": 2,
            "os": str,
            "locale": str,
            "languages": [str],
            "timezoneId": str,
            "geolocation": {"latitude": float, "longitude": float},
            "screen": {"width": int, "height": int},
            "window": {"outerWidth": int, "outerHeight": int},
            "viewport": {"width": int, "height": int},
            "deviceScaleFactor": float,
            "hardwareConcurrency": int,
            "deviceMemory": int,
            "webgl": None | dict,
            "firefoxUserPrefs": dict,
            "launchScreenConstraints": {"minWidth": int, "maxWidth": int,
                                        "minHeight": int, "maxHeight": int},
        }
    """
    user_id = normalize_user_id(user_id)
    fixed = _build_managed_browser_persona(user_id)

    # --- OS ---
    os_value: str = (
        fixed["os"]
        if fixed
        else PERSONA_OS[_deterministic_index(user_id, "os", len(PERSONA_OS))]
    )

    # --- Locale profile ---
    locale_profile: dict[str, Any] = (
        fixed["localeProfile"]
        if fixed
        else PERSONA_LOCALES[_deterministic_index(user_id, "locale", len(PERSONA_LOCALES))]
    )

    # --- Screen ---
    screen: dict[str, int] = (
        fixed["screen"]
        if fixed
        else PERSONA_SCREENS[_deterministic_index(user_id, "screen", len(PERSONA_SCREENS))]
    )

    # --- Hardware concurrency ---
    hardware_concurrency: int = (
        fixed["hardwareConcurrency"]
        if fixed
        else PERSONA_HARDWARE_CONCURRENCY[
            _deterministic_index(
                user_id, "hardware-concurrency", len(PERSONA_HARDWARE_CONCURRENCY)
            )
        ]
    )

    # --- Device memory ---
    device_memory: int = (
        fixed["deviceMemory"]
        if fixed
        else PERSONA_DEVICE_MEMORY_GB[
            _deterministic_index(user_id, "device-memory", len(PERSONA_DEVICE_MEMORY_GB))
        ]
    )

    # --- Device scale factor ---
    device_scale_factor: float = (
        fixed["deviceScaleFactor"]
        if fixed
        else PERSONA_DEVICE_SCALE_FACTORS[
            _deterministic_index(
                user_id, "device-scale-factor", len(PERSONA_DEVICE_SCALE_FACTORS)
            )
        ]
    )

    # --- Languages ---
    languages: list[str] = locale_profile.get(
        "languages",
        [locale_profile["locale"], locale_profile["locale"].split("-")[0]],
    )

    # --- WebGL (Phase 2: generated by pythonlib camoufox.webgl.sample_webgl) ---
    webgl: Any = fixed.get("webgl") if fixed else None

    # --- Assemble result ---
    result: dict[str, Any] = {
        "version": 2,
        "os": os_value,
        "locale": locale_profile["locale"],
        "languages": languages,
        "timezoneId": locale_profile["timezoneId"],
        "geolocation": locale_profile["geolocation"],
        "screen": {"width": screen["width"], "height": screen["height"]},
        "window": {
            "outerWidth": screen["width"],
            "outerHeight": screen["height"],
        },
        "viewport": {
            "width": screen["width"],
            "height": screen["height"],
        },
        "deviceScaleFactor": device_scale_factor,
        "hardwareConcurrency": hardware_concurrency,
        "deviceMemory": device_memory,
        "webgl": webgl,
        "firefoxUserPrefs": {
            "browser.startup.page": 0,
            "browser.sessionstore.resume_from_crash": True,
            "privacy.resistFingerprinting": False,
        },
        "launchScreenConstraints": {
            "minWidth": screen["width"],
            "maxWidth": screen["width"],
            "minHeight": screen["height"],
            "maxHeight": screen["height"],
        },
    }

    if webgl:
        result["webglConfig"] = [webgl["vendor"], webgl["renderer"]]

    return result
